<a href="https://colab.research.google.com/github/miriampaul/AnalysisPandasProfilingEDA/blob/main/Data_Preprocessing_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
#import datasets
dataset=pd.read_csv("/content/Data.csv")
#Features (1st few columns) and #dependent columns (last columns)
X=dataset.iloc[:,:-1].values # all columns excluding the last column
Y=dataset.iloc[:,-1].values #include only last columns
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [3]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [11]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [21]:
#Taking Care of Missing Data
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:,1:3])

In [22]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [23]:
#Encoding the categorical data

In [27]:
#Encoding the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])] , remainder='passthrough' )
X=np.array(ct.fit_transform(X))
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [28]:
#Encoding the Dependent Variable

In [30]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
Y=le.fit_transform(Y)

In [31]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [32]:
#Splitting the dataset into Training and Test Set

In [37]:
 from sklearn.model_selection import train_test_split
 X_train, X_test, Y_train, Y_test=\
 train_test_split(X, Y , test_size=0.2, random_state=1,stratify=Y)

In [38]:
X_train

array([[1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [39]:
X_test

array([[1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object)

In [40]:
Y_train

array([0, 1, 1, 0, 1, 0, 1, 0])

In [41]:
Y_test

array([1, 0])

In [42]:
#FEature Scaling #avoid features to be dominated by other features

In [43]:
#Simple Linear Regression , Multiple Linear Regression

In [45]:
#How to apply feature scaling, Standardization =X-Mean(X)/stddev [-3, +3]. Normalization=X-min(X)/max(x)-min(X)[-1, 1]

In [47]:
#Normalization recommended when normal distribution , Standardsation =works All times

In [49]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

In [50]:
X_train

array([[1.0, 0.0, 1.0, -0.5773502691896258, 1.4810949949635102,
        1.5511947816430596],
       [0.0, 1.0, 0.0, -0.5773502691896258, -0.2115849992805015,
        0.15293469678171012],
       [0.0, 1.0, 0.0, -0.5773502691896258, -0.47199730608727253,
        -0.633586600952799],
       [0.0, 1.0, 0.0, -0.5773502691896258, 0.6998580745431972,
        0.5898909733008818],
       [1.0, 0.0, 0.0, 1.7320508075688774, -1.5136465333143565,
        -1.5074991539911424],
       [1.0, 0.0, 1.0, -0.5773502691896258, -1.1230280731042,
        -0.9831516221681363],
       [0.0, 1.0, 0.0, -0.5773502691896258, 1.2206826881567392,
        1.2016297604277222],
       [1.0, 0.0, 0.0, 1.7320508075688774, -0.08137884587711598,
        -0.37141283504129596]], dtype=object)

In [51]:
X_test

array([[1.0, 0.0, 1.0, -1.0, 1.0000000000000058, 1.0],
       [1.0, 0.0, 0.0, 1.0, -0.9999999999999942, -1.0]], dtype=object)